name: Sync Docs And Deploy To Github Pages

on:
  repository_dispatch:
    types:
      - sync-deploy

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --prod
      - name: 拉取语雀&Notion&FlowUs&飞书的文档
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_IMAGE_BUCKET: ${{ secrets.COS_IMAGE_BUCKET }}
          COS_IMAGE_REGION: ${{ secrets.COS_IMAGE_REGION }}
          COS_HOST: ${{ secrets.COS_HOST }}
        run: |
          pnpm run sync:notion
      - name: 配置Git用户名邮箱
        run: |
          git config --global user.name "100759"
          git config --global user.email "2827162018@qq.com"
      - name: 提交拉取的文档到GitHub仓库
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git add .
          git commit -m "Refresh elog.cache.json" -a
      - name: 推送文档到仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: 生成静态文件
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          pnpm run docs:build
      - name: 部署到Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: .vitepress/dist
          external_repository: 100759/100759.github.io
          publish_branch: master
          commit_message: ${{ github.event.head_commit.message }}
